services:
  web:
    depends_on:
      - postgres
    build: .
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn dev
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres@postgres/webapp_dev
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust
